### ISSUE TITLE
大佬 怎么控制popup 一直显示呢

### ISSUE THREAD

**Issue by Blizzard-liu** [haiweilian/taggd-manager#18]

**Comment by haiweilian** [comment]
强制覆盖样式哇。

```css
.taggd__popup {
    display: block !important;
}
```
